// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cox_null_grad_norms_cpp
Rcpp::List cox_null_grad_norms_cpp(const arma::mat& X, int n_simu, double alpha);
RcppExport SEXP _picreg_cox_null_grad_norms_cpp(SEXP XSEXP, SEXP n_simuSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_simu(n_simuSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(cox_null_grad_norms_cpp(X, n_simu, alpha));
    return rcpp_result_gen;
END_RCPP
}
// fista_cpp
Rcpp::List fista_cpp(const arma::mat& X, const arma::vec& y, std::string family_name, std::string penalty_name, double lambda_reg, double scad_a, double mcp_gamma, bool fit_intercept, double rel_tol, double step_size_init, int max_iter, double eta_param, double delta_param, double rho, double bb_growth_cap, Rcpp::Nullable<Rcpp::NumericVector> coef_init, Rcpp::Nullable<double> intercept_init);
RcppExport SEXP _picreg_fista_cpp(SEXP XSEXP, SEXP ySEXP, SEXP family_nameSEXP, SEXP penalty_nameSEXP, SEXP lambda_regSEXP, SEXP scad_aSEXP, SEXP mcp_gammaSEXP, SEXP fit_interceptSEXP, SEXP rel_tolSEXP, SEXP step_size_initSEXP, SEXP max_iterSEXP, SEXP eta_paramSEXP, SEXP delta_paramSEXP, SEXP rhoSEXP, SEXP bb_growth_capSEXP, SEXP coef_initSEXP, SEXP intercept_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type family_name(family_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type penalty_name(penalty_nameSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_reg(lambda_regSEXP);
    Rcpp::traits::input_parameter< double >::type scad_a(scad_aSEXP);
    Rcpp::traits::input_parameter< double >::type mcp_gamma(mcp_gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type fit_intercept(fit_interceptSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< double >::type step_size_init(step_size_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type eta_param(eta_paramSEXP);
    Rcpp::traits::input_parameter< double >::type delta_param(delta_paramSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type bb_growth_cap(bb_growth_capSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type coef_init(coef_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type intercept_init(intercept_initSEXP);
    rcpp_result_gen = Rcpp::wrap(fista_cpp(X, y, family_name, penalty_name, lambda_reg, scad_a, mcp_gamma, fit_intercept, rel_tol, step_size_init, max_iter, eta_param, delta_param, rho, bb_growth_cap, coef_init, intercept_init));
    return rcpp_result_gen;
END_RCPP
}
// fista_cox_cpp
Rcpp::List fista_cox_cpp(const arma::mat& X, const arma::vec& times, const arma::vec& events, std::string penalty_name, double lambda_reg, double scad_a, double mcp_gamma, double rel_tol, double step_size_init, int max_iter, double eta_param, double delta_param, double rho, double bb_growth_cap, Rcpp::Nullable<Rcpp::NumericVector> coef_init);
RcppExport SEXP _picreg_fista_cox_cpp(SEXP XSEXP, SEXP timesSEXP, SEXP eventsSEXP, SEXP penalty_nameSEXP, SEXP lambda_regSEXP, SEXP scad_aSEXP, SEXP mcp_gammaSEXP, SEXP rel_tolSEXP, SEXP step_size_initSEXP, SEXP max_iterSEXP, SEXP eta_paramSEXP, SEXP delta_paramSEXP, SEXP rhoSEXP, SEXP bb_growth_capSEXP, SEXP coef_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type events(eventsSEXP);
    Rcpp::traits::input_parameter< std::string >::type penalty_name(penalty_nameSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_reg(lambda_regSEXP);
    Rcpp::traits::input_parameter< double >::type scad_a(scad_aSEXP);
    Rcpp::traits::input_parameter< double >::type mcp_gamma(mcp_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< double >::type step_size_init(step_size_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type eta_param(eta_paramSEXP);
    Rcpp::traits::input_parameter< double >::type delta_param(delta_paramSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type bb_growth_cap(bb_growth_capSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type coef_init(coef_initSEXP);
    rcpp_result_gen = Rcpp::wrap(fista_cox_cpp(X, times, events, penalty_name, lambda_reg, scad_a, mcp_gamma, rel_tol, step_size_init, max_iter, eta_param, delta_param, rho, bb_growth_cap, coef_init));
    return rcpp_result_gen;
END_RCPP
}
// lambda_max_cpp
double lambda_max_cpp(const arma::mat& X, const arma::vec& y, std::string family_name, bool fit_intercept);
RcppExport SEXP _picreg_lambda_max_cpp(SEXP XSEXP, SEXP ySEXP, SEXP family_nameSEXP, SEXP fit_interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type family_name(family_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type fit_intercept(fit_interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_max_cpp(X, y, family_name, fit_intercept));
    return rcpp_result_gen;
END_RCPP
}
// lambda_max_cox_cpp
double lambda_max_cox_cpp(const arma::mat& X, const arma::vec& times, const arma::vec& events);
RcppExport SEXP _picreg_lambda_max_cox_cpp(SEXP XSEXP, SEXP timesSEXP, SEXP eventsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type events(eventsSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_max_cox_cpp(X, times, events));
    return rcpp_result_gen;
END_RCPP
}
// pdb_mc_gaussian_cpp
Rcpp::List pdb_mc_gaussian_cpp(const arma::mat& X, double c_n, int n_simu, double alpha);
RcppExport SEXP _picreg_pdb_mc_gaussian_cpp(SEXP XSEXP, SEXP c_nSEXP, SEXP n_simuSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type c_n(c_nSEXP);
    Rcpp::traits::input_parameter< int >::type n_simu(n_simuSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(pdb_mc_gaussian_cpp(X, c_n, n_simu, alpha));
    return rcpp_result_gen;
END_RCPP
}
// pdb_mc_exact_cpp
Rcpp::List pdb_mc_exact_cpp(const arma::mat& X, std::string family_name, int n_simu, double alpha);
RcppExport SEXP _picreg_pdb_mc_exact_cpp(SEXP XSEXP, SEXP family_nameSEXP, SEXP n_simuSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< std::string >::type family_name(family_nameSEXP);
    Rcpp::traits::input_parameter< int >::type n_simu(n_simuSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(pdb_mc_exact_cpp(X, family_name, n_simu, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_picreg_cox_null_grad_norms_cpp", (DL_FUNC) &_picreg_cox_null_grad_norms_cpp, 3},
    {"_picreg_fista_cpp", (DL_FUNC) &_picreg_fista_cpp, 17},
    {"_picreg_fista_cox_cpp", (DL_FUNC) &_picreg_fista_cox_cpp, 15},
    {"_picreg_lambda_max_cpp", (DL_FUNC) &_picreg_lambda_max_cpp, 4},
    {"_picreg_lambda_max_cox_cpp", (DL_FUNC) &_picreg_lambda_max_cox_cpp, 3},
    {"_picreg_pdb_mc_gaussian_cpp", (DL_FUNC) &_picreg_pdb_mc_gaussian_cpp, 4},
    {"_picreg_pdb_mc_exact_cpp", (DL_FUNC) &_picreg_pdb_mc_exact_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_picreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
